object Versions {
    const val workTesting="2.7.1"
    const val hiltWork = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val hiltLifecycleViewmodel = "1.0.0-alpha03"
    const val daggerHilt = "2.40.5"
    const val napierVersion = "2.5.0"
    const val kotlinVersion = "1.6.10"
    const val kotlinxCoroutines = "1.6.0"
    const val koin = "3.1.4"
    const val apollo = "3.2.2"
    const val multiplatformPaging = "0.4.7"
    const val ktorVersion = "1.6.8"
    const val compose = "1.1.1"
    const val composeCompiler = "1.1.1"
    const val navCompose = "2.4.1"
    const val material3Version = "1.0.0-alpha09"
    const val pagingCompose = "1.0.0-alpha14"
    const val accompanist = "0.23.0"
    const val coilComposeVersion = "1.4.0"
    const val kotlinxSerializationJson = "1.3.2"
    const val junit = "4.13"
    const val sqldelightVersion = "1.5.3"
}